// Dati statici della galleria — usati come FALLBACK quando WordPress non è configurato.
// Quando colleghi WordPress (vedi lib/wordpress.js), questi dati vengono sostituiti
// automaticamente da quelli del CMS mantenendo la stessa identica forma.
//
// Campo `credit`: attribuzione della foto.
//  - null  => foto di proprietà dell'allevamento (le tue)
//  - oggetto => foto con licenza libera (placeholder da sostituire)
export const galleryItems = [
  {
    id: "cucciolata-2026",
    category: "cucciolate",
    badge: "Cucciolata disponibile",
    title: "Cucciolata Primavera 2026",
    subtitle: "Cuccioli selezionati da tartufo",
    image: "/images/lagotto-romagnolo-cucciolo-tartufo-cesto.jpg",
    width: 1408,
    height: 768,
    alt: "Cucciolo di Lagotto Romagnolo bianco e marrone seduto accanto a un cesto di tartufi nel bosco",
    desc: "Cuccioli di Lagotto Romagnolo da tartufo, socializzati in famiglia e avviati al riporto e alla ricerca dell'odore.",
    meta: [
      { l: "Disponibilità", v: "Su prenotazione" },
      { l: "Genealogia", v: "Genitori esenti displasia (HD/ED)" },
      { l: "Test genetici", v: "Esente LSD & BFJE" },
      { l: "Attitudine", v: "Avvio alla cerca dalle 5 settimane" },
    ],
    credit: null,
  },
  {
    id: "riproduttore-tartufaia",
    category: "riproduttori",
    badge: "Riproduttore",
    title: "Linea Tartufaia",
    subtitle: "Selezione genetica per la cerca",
    image: "/images/cucciolo-lagotto-cioccolato-tartufi-neri.jpg",
    width: 1408,
    height: 768,
    alt: "Lagotto Romagnolo marrone cioccolato accanto a un cesto di tartufi neri nel bosco",
    desc: "Soggetto di linea selezionata per il fiuto e la concentrazione sul lavoro: base genetica delle nostre cucciolate da tartufo.",
    meta: [
      { l: "Mantello", v: "Marrone (cioccolato)" },
      { l: "Displasia anca (HD)", v: "Esente" },
      { l: "Displasia gomito (ED)", v: "Esente" },
      { l: "Iscrizione", v: "ROI / Pedigree ENCI" },
    ],
    credit: null,
  },
  {
    id: "momenti-di-cerca",
    category: "cerca",
    badge: "Momenti di cerca",
    title: "Sul campo, nel bosco",
    subtitle: "Addestramento precoce alla cerca",
    image: "/images/cuccioli-lagotto-cerca-tartufo-bosco.jpg",
    width: 1408,
    height: 768,
    alt: "Sequenza di cuccioli di Lagotto Romagnolo durante la cerca del tartufo nel bosco",
    desc: "I nostri cuccioli durante le prime esperienze di cerca: olfatto, scavo e riporto guidati in totale serenità.",
    meta: [
      { l: "Ambiente", v: "Bosco di collina" },
      { l: "Stagione", v: "Autunno" },
      { l: "Lavoro", v: "Ricerca, scavo e riporto" },
      { l: "Età cuccioli", v: "8–12 settimane" },
    ],
    credit: null,
  },
  {
    id: "riproduttrice-bianca",
    category: "riproduttori",
    badge: "Fattrice",
    title: "Fattrice — Mantello Bianco",
    subtitle: "Struttura tipica di razza",
    image: "/images/lagotto-romagnolo-bianco-adulto.jpg",
    width: 1200,
    height: 1089,
    alt: "Lagotto Romagnolo adulto dal mantello bianco riccio in posizione da esposizione",
    desc: "Soggetto adulto dalla struttura solida e dal carattere equilibrato, esempio della tipicità del Lagotto Romagnolo.",
    meta: [
      { l: "Mantello", v: "Bianco riccio" },
      { l: "Displasia (HD/ED)", v: "Esente" },
      { l: "Carattere", v: "Equilibrato, collaborativo" },
      { l: "Iscrizione", v: "Pedigree ENCI" },
    ],
    credit: { author: "Pleple2000", license: "CC BY-SA 3.0", source: "Wikimedia Commons" },
  },
  {
    id: "lagotto-prato",
    category: "cerca",
    badge: "In natura",
    title: "Energia e Olfatto",
    subtitle: "A loro agio all'aperto",
    image: "/images/lagotto-romagnolo-prato-gioco.jpg",
    width: 1200,
    height: 800,
    alt: "Lagotto Romagnolo crema rilassato sull'erba con la lingua di fuori in un prato",
    desc: "Il Lagotto dà il meglio all'aperto: instancabile, attento e sempre pronto a collaborare con l'uomo.",
    meta: [
      { l: "Ambiente", v: "Prato / radura" },
      { l: "Attitudine", v: "Olfattiva e da riporto" },
      { l: "Energia", v: "Alta, gestibile" },
    ],
    credit: { author: "Alberto Ziveri", license: "CC BY-SA 2.0", source: "Wikimedia Commons" },
  },
  {
    id: "riproduttore-roano",
    category: "riproduttori",
    badge: "Riproduttore",
    title: "Linea Roano-Marrone",
    subtitle: "Tipicità e sostanza",
    image: "/images/lagotto-romagnolo-marrone-roano-campo.jpg",
    width: 1200,
    height: 1019,
    alt: "Lagotto Romagnolo dal mantello marrone roano in piedi in un campo",
    desc: "Riproduttore di sostanza e ossatura corretta, selezionato per trasmettere tipicità e salute alla discendenza.",
    meta: [
      { l: "Mantello", v: "Marrone roano" },
      { l: "Displasia (HD/ED)", v: "Esente" },
      { l: "Test genetici", v: "Esente patologie di razza" },
      { l: "Iscrizione", v: "ROI / Pedigree ENCI" },
    ],
    credit: { author: "Jcr13", license: "Pubblico dominio", source: "Wikimedia Commons" },
  },
  {
    id: "ritratto-bosco",
    category: "cerca",
    badge: "Momenti di cerca",
    title: "Concentrazione nel Bosco",
    subtitle: "Naso a terra, testa al lavoro",
    image: "/images/lagotto-romagnolo-ritratto-bosco.jpg",
    width: 1200,
    height: 801,
    alt: "Ritratto ravvicinato di Lagotto Romagnolo marrone in un ambiente boschivo verde",
    desc: "Lo sguardo del Lagotto sul lavoro: concentrazione, calma e quel fiuto eccezionale che lo rende il re della cerca.",
    meta: [
      { l: "Ambiente", v: "Bosco" },
      { l: "Dote", v: "Fiuto e concentrazione" },
      { l: "Indole", v: "Docile e attenta" },
    ],
    credit: { author: "Shixart1985", license: "CC BY 2.0", source: "Wikimedia Commons" },
  },
  {
    id: "cioccolato-natura",
    category: "riproduttori",
    badge: "Giovane promessa",
    title: "Giovane Cioccolato",
    subtitle: "Il futuro della selezione",
    image: "/images/lagotto-romagnolo-cioccolato-natura.jpg",
    width: 801,
    height: 1200,
    alt: "Giovane Lagotto Romagnolo dal mantello marrone cioccolato in un ambiente naturale verde",
    desc: "Un giovane soggetto in crescita: il nostro lavoro di selezione guarda al futuro, generazione dopo generazione.",
    meta: [
      { l: "Mantello", v: "Marrone cioccolato" },
      { l: "Fase", v: "In crescita / valutazione" },
      { l: "Prospettiva", v: "Futura riproduzione" },
    ],
    credit: { author: "Shixart1985", license: "CC BY 2.0", source: "Wikimedia Commons" },
  },
];

export const galleryFilters = [
  { key: "all", label: "Tutti" },
  { key: "riproduttori", label: "I nostri riproduttori" },
  { key: "cucciolate", label: "Cucciolate disponibili" },
  { key: "cerca", label: "Momenti di cerca" },
];
